foo = "bar"
iface = "iface"
String = "s"
Bool = true
Int = 1
Float64 = 1.1
Duration = 1e9
Time = "2020-03-07 12:31:19"
StringSlice = ["s1", "s2"]
[StringMap]
String = "Map"
[StringMapString]
String = "String"
