# Default Queue Connection Name
Default = "testing"

# Queue Connections
# Here you may configure the connection information for each server that
# is used by your application. A default configuration has been added
# for each back-end shipped with Dawn. You are free to add more.
#
# Drivers: "sync", "database", "redis", "null"

[Connections]
[Connections.Sync]
Driver = "sync"

[Connections.Testing]
Driver = "database"
Connection = "testing"
Table = "sys_jobs"
Queue = "default"
RetryAfter = 90e9

[Connections.Redis]
Driver = "Redis"
Preload = false
Connection = "queue"
Queue = "default"
RetryAfter = 90e9

# Failed Queue Jobs
# These options configure the behavior of failed queue job logging so you
# can control which database and table are used to store the jobs that
# have failed. You may change them to any database / table you wish.
[Failed]
Database = "testing"
Table = "sys_failed_jobs"
